# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Export

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  modrinth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest
    
    - name: Export Modrinth
      run: $(go env GOPATH)/bin/packwiz modrinth export -o hajpack.mrpack

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hajpack
        path: hajpack.mrpack
      
  curseforge: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest
    
    - name: Export Curseforge
      run: $(go env GOPATH)/bin/packwiz curseforge export -o hajpack.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hajpack
        path: hajpack.zip